#ifndef PAGE_FAULT_ACTUAL_REASON
#define PAGE_FAULT_ACTUAL_REASON

namespace hardware {

enum PageFaultActualReason {
    PAGE_NOT_PRESENT,
    READONLY_VIOLATION,
    PRIVILEGE_VIOLATION,
    RESERVED_WRITE_VIOLATION,
    INSTRUCTION_FETCH,
    STACK_OVERFLOW,
    UNKNOWN_PROTECTION_VIOLATION,
    INVALID_ADDRESS_SPACE
};

}

#endif